"""
Blender Generator Module for CNC Box Creator.
Handles generation of Blender Python scripts for visualization.
"""

from utils import convert_to_inches, MARGIN_INCHES

def generate_blender_script(version, config, rail_paths, geom_front, geom_back):
    """
    Generate a complete Blender Python script that recreates the shadowbox assembly.

    This script can be opened directly in Blender's Text Editor and run to create:
    - All 6 pieces with accurate finger joint geometry
    - Boolean cuts for Window (Front Bezel), Holes (Back Panel), and Rabbets (all rails)
    - Correct positioning in assembled orientation
    - Two plywood materials (wide face and end grain)
    - Area light setup per JLS specifications
    - Viewport set to Material Preview and JLS Workspace
    """

    # Calculate dimensions from config
    total_width_in = convert_to_inches(config['TOTAL_WIDTH'])
    total_height_in = convert_to_inches(config['TOTAL_HEIGHT'])
    box_depth_in = convert_to_inches(config['BOX_DEPTH'])
    stock_thk_in = convert_to_inches(config['STOCK_THICKNESS'])
    
    # Window dimensions (retrieved from config or defaulted)
    window_width_in = config.get('WINDOW_WIDTH_IN', total_width_in - 3.0)
    window_height_in = config.get('WINDOW_HEIGHT_IN', total_height_in - 3.0)
    
    # Rabbet dimensions
    front_rabbet_w_in = config.get('FRONT_RABBET_WIDTH', 0.3)
    front_rabbet_d_in = config.get('FRONT_RABBET_DEPTH', 0.3)
    back_rabbet_w_in = config.get('BACK_RABBET_WIDTH', 0.3)
    back_rabbet_d_in = config.get('BACK_RABBET_DEPTH', 0.3)
    
    # Extract hole data from geom_back
    back_holes = geom_back.get('holes', [])
    back_hole_r_in = geom_back.get('hole_r', 0.1)
    back_rim_width_in = geom_back.get('rim_width', 0.3)
    
    # Extract front bezel rim width (calculated in App)
    front_rim_width_in = config.get('FRONT_RIM_WIDTH_IN', 0.3) # Fallback if missing
    if 'FRONT_RIM_WIDTH_M' in config:
         front_rim_width_in = config['FRONT_RIM_WIDTH_M'] / 0.0254

    # Convert to meters for Blender
    total_width_m = total_width_in * 0.0254
    total_height_m = total_height_in * 0.0254
    box_depth_m = box_depth_in * 0.0254
    stock_thk_m = stock_thk_in * 0.0254
    
    window_width_m = window_width_in * 0.0254
    window_height_m = window_height_in * 0.0254
    
    front_rabbet_w_m = front_rabbet_w_in * 0.0254
    front_rabbet_d_m = front_rabbet_d_in * 0.0254
    back_rabbet_w_m = back_rabbet_w_in * 0.0254
    back_rabbet_d_m = back_rabbet_d_in * 0.0254
    
    back_hole_r_m = back_hole_r_in * 0.0254
    back_rim_width_m = back_rim_width_in * 0.0254
    front_rim_width_m = front_rim_width_in * 0.0254
    
    # Convert hole positions to meters (subtract margin first, then convert)
    holes_m = []
    for hx, hy in back_holes:
        hx_in = hx - MARGIN_INCHES
        hy_in = hy - MARGIN_INCHES
        holes_m.append((hx_in * 0.0254, hy_in * 0.0254))
        
    # Cleat Mounting Holes logic (for Blender)
    # We need to pass the 'cleat_hole_positions' if we want to model them on the back panel
    # The `back_holes` above are user-defined generic holes. 
    # v1.09 added automatic cleat mounting holes to `generate_back_panel_parts` -> `BACK_PANEL_HOLES_THROUGH`
    # Ideally, we should add these to the `holes_m` list if they aren't already there.
    # But `geom_back` passed here comes from `generate_back_panel_parts`.
    # Let's check `geom_back` structure in `generate_back_panel_parts`.
    # It has 'holes'. In v1.09, we commented out adding them to 'holes' list?
    # No, we skipped adding them to `geometry_data['holes']`.
    # Correction: We MUST add them to `geometry_data['holes']` so they appear here.
    # OR we handle them separately.
    # Let's handle them separately for clarity in Blender script.
    
    # HACK: Re-calculate or pass. 
    # We will recalculate in Blender script or Python? 
    # Python is easier.
    cleat_holes_m = []
    if config.get('CLEATS_ENABLED', True):
        c_w_in = min(total_width_in * 0.80, 48.0)
        c_h_in = 4.0
        # Calc Holes
        # Y = height_in / 3.0 (From top)
        # In Blender (Center Origin), Top is +H/2.
        # Hole Y = (H/2) - (H/3) = H/6.
        # X: Centered.
        
        # We will calc in Blender script for precision relative to object bounds.
        pass

    script = f'''#!/usr/bin/env python3
"""
OPEN ME IN BLENDER - Shadowbox Assembly v{version}
=========================================================
Generated by CNC Generator - Carbide-Optimized v{version}

This script creates a complete 3D visualization of the shadowbox assembly
with accurate finger joint geometry and Boolean cuts for:
- Window opening in Front Bezel
- Screw holes in Back Panel  
- Rabbet channels in all rails

INSTRUCTIONS:
1. Open Blender
2. Switch to Scripting workspace (or open a Text Editor panel)
3. Open this file (Text > Open)
4. Click "Run Script" or press Alt+P

The script will create:
- All 6 pieces (Top Rail, Bottom Rail, Left Rail, Right Rail, Front Bezel, Back Panel)
- Boolean cuts for Window, Holes, and Rabbets
- Positioned in assembled orientation
- Two plywood materials: wide face (#E2CBAD) and end grain (#C0AD93)
- Area light for visualization
- Imperial units (inches) configured
- Viewport set to Material Preview with JLS Workspace
"""

import bpy
import bmesh
import re
from mathutils import Vector, Euler
import math

# ==============================================================================
# CONFIGURATION (from your CNC Generator settings)
# ==============================================================================
CONFIG = {{
    'TOTAL_WIDTH_IN': {total_width_in:.4f},
    'TOTAL_HEIGHT_IN': {total_height_in:.4f},
    'BOX_DEPTH_IN': {box_depth_in:.4f},
    'STOCK_THICKNESS_IN': {stock_thk_in:.4f},
    'STOCK_THICKNESS_M': {stock_thk_m:.6f},
    'TOTAL_WIDTH_M': {total_width_m:.6f},
    'TOTAL_HEIGHT_M': {total_height_m:.6f},
    'BOX_DEPTH_M': {box_depth_m:.6f},
    'WINDOW_WIDTH_M': {window_width_m:.6f},
    'WINDOW_HEIGHT_M': {window_height_m:.6f},
    'FRONT_RABBET_WIDTH_M': {front_rabbet_w_m:.6f},
    'FRONT_RABBET_DEPTH_M': {front_rabbet_d_m:.6f},
    'BACK_RABBET_WIDTH_M': {back_rabbet_w_m:.6f},
    'BACK_RABBET_DEPTH_M': {back_rabbet_d_m:.6f},
    'BACK_HOLE_RADIUS_M': {back_hole_r_m:.6f},
    'BACK_RIM_WIDTH_M': {back_rim_width_m:.6f},
    'FRONT_RIM_WIDTH_M': {front_rim_width_m:.6f},
    'CLEATS_ENABLED': {bool(config.get('CLEATS_ENABLED', True))},
    'HATCH_ENABLED': {bool(config.get('HATCH_ENABLED', False))},
    'HATCH_WIDTH_PCT': {config.get('HATCH_WIDTH_PCT', 50.0)},
    'HATCH_HEIGHT_PCT': {config.get('HATCH_HEIGHT_PCT', 33.0)},
    'HATCH_RAISE_IN': {config.get('HATCH_RAISE_IN', 0.0)},  # M4 FIX: was HATCH_RAISE (never set) -> always 0
    'BOTTOM_HATCH_ENABLED': {bool(config.get('BOTTOM_HATCH_ENABLED', False))},  # H3 FIX: keys were omitted entirely
    'BOTTOM_HATCH_WIDTH': {config.get('BOTTOM_HATCH_WIDTH', 0.0)},
    'BOTTOM_HATCH_HEIGHT': {config.get('BOTTOM_HATCH_HEIGHT', 0.0)},
    'BOTTOM_HATCH_X_PCT': {config.get('BOTTOM_HATCH_X_PCT', 50.0)},
}}

# Back panel hole positions (in meters, relative to panel origin at bottom-left)
BACK_PANEL_HOLES = {holes_m}

# SVG MARGIN used in path generation (2 inches)
MARGIN_IN = 2.0

# Plywood colors (hex to RGB 0-1)
COLOR_WIDE_FACE = (0xE2/255, 0xCB/255, 0xAD/255, 1.0)  # #E2CBAD
COLOR_END_GRAIN = (0xC0/255, 0xAD/255, 0x93/255, 1.0)  # #C0AD93

# ==============================================================================
# SVG PATH DATA (embedded from generated files)
# ==============================================================================
SVG_PATHS = {{
    'TOP_RAIL': """{rail_paths.get('TOP', 'M 0 0 Z')}""",
    'BOTTOM_RAIL': """{rail_paths.get('BOTTOM', 'M 0 0 Z')}""",
    'LEFT_RAIL': """{rail_paths.get('LEFT', 'M 0 0 Z')}""",
    'RIGHT_RAIL': """{rail_paths.get('RIGHT', 'M 0 0 Z')}""",
}}

# ==============================================================================
# HELPER FUNCTIONS
# ==============================================================================

def parse_svg_path(path_d, margin_offset=2.0):
    """Parse SVG path d attribute into list of (x, y) vertices in inches, then convert to meters."""
    vertices = []
    commands = re.findall(r'([MLZ])\\s*([\\d.\\-\\s]*)', path_d)

    for cmd, coords_str in commands:
        if cmd == 'Z':
            continue
        coords = coords_str.strip().split()
        if len(coords) >= 2:
            x_in = float(coords[0]) - margin_offset
            y_in = float(coords[1]) - margin_offset
            x_m = x_in * 0.0254
            y_m = y_in * 0.0254
            vertices.append((x_m, y_m))

    return vertices

def create_plywood_materials():
    """Create the two plywood materials: wide face and end grain."""

    # Wide face material (#E2CBAD)
    mat_wide = bpy.data.materials.new(name="Plywood_Wide_Face")
    mat_wide.use_nodes = True
    nodes = mat_wide.node_tree.nodes
    nodes.clear()
    output = nodes.new('ShaderNodeOutputMaterial')
    principled = nodes.new('ShaderNodeBsdfPrincipled')
    principled.inputs['Base Color'].default_value = COLOR_WIDE_FACE
    principled.inputs['Roughness'].default_value = 0.6
    mat_wide.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    # End grain material (#C0AD93 - darker)
    mat_end = bpy.data.materials.new(name="Plywood_End_Grain")
    mat_end.use_nodes = True
    nodes = mat_end.node_tree.nodes
    nodes.clear()
    output = nodes.new('ShaderNodeOutputMaterial')
    principled = nodes.new('ShaderNodeBsdfPrincipled')
    principled.inputs['Base Color'].default_value = COLOR_END_GRAIN
    principled.inputs['Roughness'].default_value = 0.7
    mat_end.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    return mat_wide, mat_end

def get_face_dominant_axis(face_normal):
    """Determine which axis a face normal is most aligned with."""
    abs_normal = [abs(face_normal.x), abs(face_normal.y), abs(face_normal.z)]
    max_idx = abs_normal.index(max(abs_normal))
    return ['X', 'Y', 'Z'][max_idx]

def apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_axes):
    """
    Apply end grain material to faces perpendicular to specified axes.

    end_grain_axes: list of axes ('X', 'Y', 'Z') where face normals pointing
                    along these axes should get the end grain material.
    """
    if obj.type != 'MESH':
        return

    # Ensure object has both materials
    obj.data.materials.clear()
    obj.data.materials.append(mat_wide)  # Index 0
    obj.data.materials.append(mat_end)   # Index 1

    # Use bmesh to analyze and assign materials per face
    bm = bmesh.new()
    bm.from_mesh(obj.data)
    bm.faces.ensure_lookup_table()

    for face in bm.faces:
        # Get face normal in world space (after transforms applied)
        normal_world = obj.matrix_world.to_3x3() @ face.normal
        dominant_axis = get_face_dominant_axis(normal_world)

        if dominant_axis in end_grain_axes:
            face.material_index = 1  # End grain
        else:
            face.material_index = 0  # Wide face

    bm.to_mesh(obj.data)
    bm.free()
    obj.data.update()

def create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis='Z'):
    """Create a 3D mesh by extruding a 2D profile and link to collection."""
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)

    # IMPORTANT: Link to collection immediately so it exists in the scene
    collection.objects.link(obj)

    bm = bmesh.new()

    bottom_verts = []
    for v in vertices:
        if extrude_axis == 'Z':
            vert = bm.verts.new((v[0], v[1], 0))
        elif extrude_axis == 'Y':
            vert = bm.verts.new((v[0], 0, v[1]))
        elif extrude_axis == 'X':
            vert = bm.verts.new((0, v[0], v[1]))
        bottom_verts.append(vert)

    bm.verts.ensure_lookup_table()

    if len(bottom_verts) >= 3:
        try:
            bm.faces.new(bottom_verts)
        except:
            pass

    if extrude_axis == 'Z':
        extrude_vec = Vector((0, 0, thickness_m))
    elif extrude_axis == 'Y':
        extrude_vec = Vector((0, thickness_m, 0))
    elif extrude_axis == 'X':
        extrude_vec = Vector((thickness_m, 0, 0))

    ret = bmesh.ops.extrude_face_region(bm, geom=bm.faces[:])
    verts = [e for e in ret['geom'] if isinstance(e, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, verts=verts, vec=extrude_vec)

    bm.to_mesh(mesh)
    bm.free()
    mesh.update()

    return obj

def create_simple_box(name, width_m, height_m, depth_m, collection):
    """Create a simple box mesh and link to specified collection."""
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)

    # Link to our collection
    collection.objects.link(obj)

    # Create box geometry using bmesh
    bm = bmesh.new()
    bmesh.ops.create_cube(bm, size=1.0)
    bm.to_mesh(mesh)
    bm.free()

    # Set dimensions
    obj.dimensions = (width_m, depth_m, height_m)

    return obj

def create_cylinder_cutter(name, radius_m, depth_m, collection, segments=32):
    """Create a cylinder mesh for Boolean cutting operations."""
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    
    bm = bmesh.new()
    bmesh.ops.create_cone(
        bm,
        cap_ends=True,
        cap_tris=False,
        segments=segments,
        radius1=radius_m,
        radius2=radius_m,
        depth=depth_m
    )
    bm.to_mesh(mesh)
    bm.free()
    
    return obj

def apply_boolean_difference(target_obj, cutter_obj, delete_cutter=True):
    """Apply a boolean difference modifier to cut cutter from target."""
    success = False
    try:
        # Ensure cutter has transforms applied
        bpy.context.view_layer.objects.active = cutter_obj
        cutter_obj.select_set(True)
        bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
        cutter_obj.select_set(False)
        
        # Add boolean modifier
        bool_mod = target_obj.modifiers.new(name="Boolean_Cut", type='BOOLEAN')
        bool_mod.operation = 'DIFFERENCE'
        bool_mod.object = cutter_obj
        bool_mod.solver = 'EXACT'  # Use EXACT solver (required for Blender 4.x)
        
        # Apply the modifier
        bpy.context.view_layer.objects.active = target_obj
        target_obj.select_set(True)
        bpy.ops.object.modifier_apply(modifier=bool_mod.name)
        target_obj.select_set(False)
        success = True
    except Exception as e:
        print(f"    WARNING: Boolean operation failed: {{e}}")
        # Remove the modifier if it exists but failed to apply
        if "Boolean_Cut" in target_obj.modifiers:
            target_obj.modifiers.remove(target_obj.modifiers["Boolean_Cut"])
    
    # Always delete the cutter to clean up
    if delete_cutter:
        try:
            bpy.data.objects.remove(cutter_obj, do_unlink=True)
        except:
            pass
    
    return success

def remove_inner_cap_faces(obj, inner_bound_x, inner_bound_z):
    """Remove cap faces inside a window opening after Boolean cut."""
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    
    faces_to_delete = []
    for face in bm.faces:
        # Check if all vertices are within the inner bounds
        all_inner = True
        for vert in face.verts:
            if abs(vert.co.x) > inner_bound_x + 0.001 or abs(vert.co.z) > inner_bound_z + 0.001:
                all_inner = False
                break
        if all_inner:
            faces_to_delete.append(face)
    
    for face in faces_to_delete:
        bm.faces.remove(face)
    
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    
    return len(faces_to_delete)

def remove_hole_cap_faces(obj, hole_positions, y_front, y_back):
    """Remove cap faces inside holes after Boolean cuts."""
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    
    faces_to_delete = []
    for face in bm.faces:
        centroid = face.calc_center_median()
        y_vals = [v.co.y for v in face.verts]
        all_front = all(abs(y - y_front) < 0.001 for y in y_vals)
        all_back = all(abs(y - y_back) < 0.001 for y in y_vals)
        
        if all_front or all_back:
            for hx, hz in hole_positions:
                dist = ((centroid.x - hx)**2 + (centroid.z - hz)**2)**0.5
                if dist < 0.01:  # Within 10mm of hole center
                    faces_to_delete.append(face)
                    break
    
    for face in faces_to_delete:
        bm.faces.remove(face)
    
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    
    return len(faces_to_delete)

def create_front_bezel_with_window(name, width_m, height_m, thickness_m, 
                                    window_w_m, window_h_m, rim_width_m, collection):
    """
    Create the front bezel with window cutout.
    
    The bezel has:
    1. Outer dimensions = total_width x total_height
    2. Window cutout = Explicitly sized, centered
    """
    # Create main panel
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    
    # Apply scale to get actual geometry
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    
    # Get bezel center Y position (needed for cutter placement)
    mesh = obj.data
    bezel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_center_y = (bezel_y_min + bezel_y_max) / 2
    
    # Create window cutter (through-cut)
    # window_w and window_h are passed in explicitly now
    window_w = window_w_m
    window_h = window_h_m
    
    if window_w > 0 and window_h > 0:
        # Create cutter mesh using bmesh at correct dimensions
        cutter_mesh = bpy.data.meshes.new(name + "_window_cutter_mesh")
        window_cutter = bpy.data.objects.new(name + "_window_cutter", cutter_mesh)
        collection.objects.link(window_cutter)
        
        bm = bmesh.new()
        hw = window_w / 2
        hd = thickness_m * 1.5  # Go through the panel
        hh = window_h / 2
        
        # Create 8 vertices of the box centered at origin
        verts = [
            bm.verts.new((-hw, -hd, -hh)),
            bm.verts.new(( hw, -hd, -hh)),
            bm.verts.new(( hw,  hd, -hh)),
            bm.verts.new((-hw,  hd, -hh)),
            bm.verts.new((-hw, -hd,  hh)),
            bm.verts.new(( hw, -hd,  hh)),
            bm.verts.new(( hw,  hd,  hh)),
            bm.verts.new((-hw,  hd,  hh)),
        ]
        bm.verts.ensure_lookup_table()
        
        # Create 6 faces
        bm.faces.new([verts[0], verts[1], verts[2], verts[3]])  # bottom
        bm.faces.new([verts[4], verts[7], verts[6], verts[5]])  # top
        bm.faces.new([verts[0], verts[4], verts[5], verts[1]])  # front
        bm.faces.new([verts[2], verts[6], verts[7], verts[3]])  # back
        bm.faces.new([verts[0], verts[3], verts[7], verts[4]])  # left
        bm.faces.new([verts[1], verts[5], verts[6], verts[2]])  # right
        
        bm.to_mesh(cutter_mesh)
        bm.free()
        
        # Position cutter at bezel center Y
        window_cutter.location = (0, bezel_center_y, 0)
        
        # Apply boolean to cut window
        apply_boolean_difference(obj, window_cutter, delete_cutter=True)
        
        # Remove inner cap faces that close the window opening
        # v1.15: Removed manual face removal to ensure watertight geometry. 
        # The Boolean Difference (Exact Solver) handles this correctly on its own now.
        
        print(f"    - Window cut: {{window_w*39.37:.2f}} x {{window_h*39.37:.2f}} inches")
    
    return obj

def create_back_panel_with_holes(name, width_m, height_m, thickness_m,
                                  hole_positions, hole_radius_m, rim_width_m, collection):
    """
    Create the back panel with screw holes.
    
    The panel has:
    1. Outer dimensions = total_width x total_height
    2. Screw holes at specified positions
    """
    # Create main panel
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    
    # Apply scale to get actual geometry
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    
    # Get panel Y bounds for cap face removal later
    mesh = obj.data
    panel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_center_y = (panel_y_min + panel_y_max) / 2
    
    # Track hole positions in panel-centered coordinates for cap removal
    centered_hole_positions = []
    
    # Create and apply hole cutters
    if hole_positions and hole_radius_m > 0:
        print(f"    - Cutting {{len(hole_positions)}} screw holes (r={{hole_radius_m*39.37:.3f}} in)")
        
        for i, (hx, hy) in enumerate(hole_positions):
            # Create cylinder cutter
            hole_cutter = create_cylinder_cutter(
                f"{{name}}_hole_{{i}}", 
                hole_radius_m, 
                thickness_m * 3,  # Go through the panel
                collection,
                segments=16
            )
            
            # Rotate to align with Y axis (panel faces front/back)
            hole_cutter.rotation_euler = (math.pi/2, 0, 0)
            
            # Position hole - convert from bottom-left origin to center origin
            hole_x = hx - width_m/2
            hole_z = hy - height_m/2
            hole_cutter.location = (hole_x, panel_center_y, hole_z)
            centered_hole_positions.append((hole_x, hole_z))
            
            # Apply rotation and location before boolean
            bpy.context.view_layer.objects.active = hole_cutter
            hole_cutter.select_set(True)
            bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
            hole_cutter.select_set(False)
            
            # Apply boolean
            apply_boolean_difference(obj, hole_cutter, delete_cutter=True)
        
        # Remove cap faces inside holes
        # Get updated Y bounds after boolean
        mesh = obj.data
        y_front = min(v.co.y for v in mesh.vertices)
        y_back = max(v.co.y for v in mesh.vertices)
        
        caps_removed = remove_hole_cap_faces(obj, centered_hole_positions, y_front, y_back)
        print(f"    - Removed {{caps_removed}} hole cap faces")
    
    return obj

def create_rail_with_rabbets(name, vertices, thickness_m, collection,
                              front_rabbet_w_m, front_rabbet_d_m,
                              back_rabbet_w_m, back_rabbet_d_m,
                              rail_length_m, rail_depth_m, extrude_axis='Z'):
    """
    Create a rail from SVG profile vertices.
    
    Note: Rabbet cuts on rails are skipped for now as the complex finger joint
    geometry makes Boolean operations unreliable. The visual representation 
    still accurately shows the finger joints which are the key feature.
    """
    # Create base rail from profile
    if len(vertices) >= 3:
        obj = create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis)
    else:
        # Fallback to simple box
        obj = create_simple_box(name, rail_length_m, thickness_m, rail_depth_m, collection)
    
    return obj

# ==============================================================================
# MAIN ASSEMBLY FUNCTION
# ==============================================================================

def create_shadowbox_assembly():
    """Create the complete Shadowbox assembly with Boolean cuts."""

    print("=" * 60)
    print("Creating Shadowbox Assembly v{version}")
    print("With Boolean cuts for Window, Holes, and Rabbets")
    print("=" * 60)

    # 1. SETUP SCENE
    print("\\n[1/8] Setting up scene...")

    bpy.context.scene.unit_settings.system = 'IMPERIAL'
    bpy.context.scene.unit_settings.length_unit = 'INCHES'
    bpy.context.scene.render.engine = 'CYCLES'
    bpy.context.scene.cycles.samples = 16
    bpy.context.scene.cycles.preview_samples = 32

    # Set World background strength (User Request)
    if bpy.context.scene.world and bpy.context.scene.world.node_tree:
        bg_node = bpy.context.scene.world.node_tree.nodes.get("Background")
        if bg_node:
            bg_node.inputs[1].default_value = 0.02

    # Create collection
    collection = bpy.data.collections.new("Shadowbox Assembly")
    bpy.context.scene.collection.children.link(collection)

    # Make it active
    bpy.context.view_layer.active_layer_collection = bpy.context.view_layer.layer_collection.children[collection.name]

    # 2. CREATE PLYWOOD MATERIALS
    print("[2/8] Creating plywood materials...")

    mat_wide, mat_end = create_plywood_materials()
    print(f"  - Wide face: #E2CBAD")
    print(f"  - End grain: #C0AD93")

    # 3. CREATE RAILS WITH RABBETS
    print("[3/8] Creating rails with rabbet channels...")

    stock_thk = CONFIG['STOCK_THICKNESS_M']
    total_w = CONFIG['TOTAL_WIDTH_M']
    total_h = CONFIG['TOTAL_HEIGHT_M']
    box_d = CONFIG['BOX_DEPTH_M']
    front_rab_w = CONFIG['FRONT_RABBET_WIDTH_M']
    front_rab_d = CONFIG['FRONT_RABBET_DEPTH_M']
    back_rab_w = CONFIG['BACK_RABBET_WIDTH_M']
    back_rab_d = CONFIG['BACK_RABBET_DEPTH_M']

    # H4 FIX: half extents defined here, before the cleat/hatch sections (5b/5c/5d) use them.
    # They were previously defined only in section 6, ~200 lines below their first use,
    # which raised NameError once the feature gates (H3) actually let those sections run.
    half_w = total_w / 2
    half_h = total_h / 2
    half_d = box_d / 2

    parts = {{}}

    # TOP RAIL
    print("  - Top Rail")
    top_verts = parse_svg_path(SVG_PATHS['TOP_RAIL'])
    parts['TOP'] = create_rail_with_rabbets(
        "Box_Top_Rail", top_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_w, box_d, 'Z'
    )

    # BOTTOM RAIL
    print("  - Bottom Rail")
    bot_verts = parse_svg_path(SVG_PATHS['BOTTOM_RAIL'])
    parts['BOTTOM'] = create_rail_with_rabbets(
        "Box_Bottom_Rail", bot_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_w, box_d, 'Z'
    )

    # LEFT RAIL
    print("  - Left Rail")
    left_verts = parse_svg_path(SVG_PATHS['LEFT_RAIL'])
    parts['LEFT'] = create_rail_with_rabbets(
        "Box_Left_Rail", left_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_h, box_d, 'Z'
    )
    parts['LEFT'].rotation_euler = (0, math.radians(90), 0)

    # RIGHT RAIL
    print("  - Right Rail")
    right_verts = parse_svg_path(SVG_PATHS['RIGHT_RAIL'])
    parts['RIGHT'] = create_rail_with_rabbets(
        "Box_Right_Rail", right_verts, stock_thk, collection,
        front_rab_w, front_rab_d, back_rab_w, back_rab_d,
        total_h, box_d, 'Z'
    )
    parts['RIGHT'].rotation_euler = (0, math.radians(-90), 0)

    # 4. CREATE FRONT BEZEL WITH WINDOW
    print("[4/8] Creating Front Bezel with window cutout...")
    parts['FRONT'] = create_front_bezel_with_window(
        "Box_Front_Bezel",
        total_w, total_h, stock_thk,
        CONFIG['WINDOW_WIDTH_M'],
        CONFIG['WINDOW_HEIGHT_M'],
        CONFIG['FRONT_RIM_WIDTH_M'],
        collection
    )

    # 5. CREATE BACK PANEL WITH HOLES
    print("[5/8] Creating Back Panel with screw holes...")
    parts['BACK'] = create_back_panel_with_holes(
        "Box_Back_Panel",
        total_w, total_h, stock_thk,
        BACK_PANEL_HOLES,
        CONFIG['BACK_HOLE_RADIUS_M'],
        CONFIG['BACK_RIM_WIDTH_M'],
        collection
    )

    # 5b. CREATE CLEATS (Restored v1.13)
    # Check if enabled
    if CONFIG.get('CLEATS_ENABLED', False):  # H3 FIX: was == 'True' (bool never equals str) -> never ran
        print("[5b/8] Creating French Cleats...")
        # Cleats Dims: 0.75" thick (or stock), 3" tall? No, usually 45 deg.
        # User Specs? usually ~3 inches height.
        # Let's use standard default: 75mm tall (~3 in).
        cw_m = total_w - (20 * 0.0254) # Inset from sides? Or Full Width?
        # Internal Width = Total - 2*Stock.
        inner_w = total_w - (2 * stock_thk)
        # Cleat usually spans inner width minus clearance.
        cw = inner_w - (0.01) # 1cm clearance
        ch = 3.0 * 0.0254 # 3 inches height
        
        # 1. Box Cleat (Mounted on Box)
        cleat_obj_box = create_french_cleat("Box_Cleat_Box", cw, ch, stock_thk, collection, is_wall_part=False)
        
        # Position:
        # X: Centered.
        # Y: Box Cleat is Inside. Back Face against Back Panel.
        # Back Panel Inner Face Y = half_d - stock_thk/2 - stock_thk? 
        # Back Panel Center Y = half_d + stock_thk/2.
        # Back Panel Inner Face = half_d.
        # Box Cleat Back Face = half_d.
        # Box Cleat Extruded width (X). Box Cleat Thickness (Y).
        # We need to rotate it to match orientation.
        # Cleat Profile was in XY plane extruded X?
        # Let's check `create_french_cleat` logic.
        # It extrudes along X. Profile in YZ.
        # Perfect.
        # Box Cleat Back is at Y=0.
        # We want Back at Y = half_d.
        # But wait, Box Cleat attaches to the BACK of the box?
        # Usually French Cleat is on the OUTSIDE of the Back Panel?
        # If so, Y = half_d + stock_thk.
        # "Recalculate": Box Cleat is mounted to the Back Panel.
        # Does it stick out? Yes.
        # So Position Y = half_d + stock_thk.
        
        box_cleat_y = half_d + stock_thk
        
        # Height Z: Near top?
        # 2 inches from top inner edge?
        # Top Inner Edge = half_h - stock_thk.
        # Cleat Top = half_h - stock_thk.
        # Cleat Height = ch.
        # Cleat Center Z? No, Origin is Bottom-Back.
        # So Origin Z = (half_h - stock_thk) - ch.
        
        box_cleat_z = (half_h - stock_thk) - ch
        
        cleat_obj_box.location = (0, box_cleat_y, box_cleat_z)
        # Origin was center X? Yes (hw logic).
        
        parts['CLEAT_BOX'] = cleat_obj_box
        
        # 2. Wall Cleat (Mated)
        cleat_obj_wall = create_french_cleat("Box_Cleat_Wall", cw, ch, stock_thk, collection, is_wall_part=True)
        # Mated Position:
        # Wall Cleat engages Box Cleat.
        # It is "Behind" Box Cleat (further +Y).
        # Y = box_cleat_y + ? 
        # They overlap in space if perfectly mated?
        # Wall Cleat Back is against Wall.
        # Box Cleat Back is against Box.
        # Thicknesses stack? No, they interlock.
        # Effective Stack Thickness = 1 * Stock (since 45 deg cut).
        # So Wall Surface is at Box_Back_Y + Stock.
        # Wall Cleat Location (Back Face) = Box_Back_Y + Stock.
        # Height: Matches engagement.
        cleat_obj_wall.location = (0, box_cleat_y + stock_thk, box_cleat_z)
        
        parts['CLEAT_WALL'] = cleat_obj_wall

    # 5c. CREATE BOTTOM ACCESS HATCH (v1.25)
    if CONFIG.get('BOTTOM_HATCH_ENABLED', False):  # H3 FIX: was == 'True' -> never ran
        print("[5c/8] Creating Bottom Access Hatch...")
        # Dims from Config (mm -> in -> m)
        bh_w_m = CONFIG.get('BOTTOM_HATCH_WIDTH', 0) * 0.001 # stored in mm in CONFIG?
        bh_h_m = CONFIG.get('BOTTOM_HATCH_HEIGHT', 0) * 0.001
        # Wait, CONFIG usually stores raw values. Main script converted to inches/meters for passing?
        # In blender_generator.py:
        # CONFIG dictionary is populated with PRE-CALCULATED 'IN' and 'M' values in the main script call.
        # BUT 'BOTTOM_HATCH_WIDTH' might just be the raw value from the UI vars?
        # Let's check how main script calls it.
        # Main script passes `CONFIG`.
        # `CONFIG` contains 'BOTTOM_HATCH_WIDTH' (mm, float).
        # So we need to convert.
        
        bh_w_mm = float(CONFIG.get('BOTTOM_HATCH_WIDTH', 0))
        bh_h_mm = float(CONFIG.get('BOTTOM_HATCH_HEIGHT', 0))
        bh_x_pct = float(CONFIG.get('BOTTOM_HATCH_X_PCT', 50.0))
        
        bh_w_m = bh_w_mm * 0.001
        bh_h_m = bh_h_mm * 0.001
        
        # Flange logic
        glue_gap = 0.0005 # approx 0.5mm
        flange_w = (stock_thk / 2.0) - glue_gap
        if flange_w < 0.001: flange_w = 0.001

        # Create Hatch Lid Object
        bh_obj = create_hatch_lid("Box_Bottom_Hatch_Lid", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        # On Bottom Rail.
        # Bottom Rail Y (Depth) center = 0.
        # Bottom Rail Z (Height) = -half_h + stock/2.
        # Hatch is "In" the rail.
        # Rail Thickness is Z.
        # Hatch Thickness is Z.
        # Hatch should be flush with Rail Bottom (Outside)? Or Rail Top (Inside)?
        # Usually flush with Outside (Bottom).
        # Rail Bottom Z = -half_h.
        # Hatch Bottom Z = -half_h.
        # Hatch constructed centered.
        # Move to Z = -half_h + stock/2. (Same as Rail Center).
        
        # X Position:
        # bh_x_pct along Rail Width.
        # Rail Width = Total Width - 2*Stock.
        # Rail starts at X = -(TotalW/2) + Stock.
        # 0% = Left Inner Edge. 100% = Right Inner Edge.
        # Inner Width = TotalW - 2*Stock.
        # X = (LeftEdge) + (Pct * InnerWidth).
        # LeftEdge = -(total_w/2) + stock_thk.
        
        inner_w = total_w - (2 * stock_thk)
        bx = (-(total_w/2) + stock_thk) + (bh_x_pct / 100.0 * inner_w)
        
        # Y Position: Centered in Depth (Y=0).
        
        bh_obj.location = (bx, 0, -half_h + stock_thk/2)
        # Orientation: create_hatch_lid makes it flat (Y-up thickness).
        # Wait, create_hatch_lid scales (w, thk/2, h). Y is thickness.
        # Bottom Rail is flat?
        # create_rail_with_rabbets for BOTTOM:
        # profile (Y, Z in SVG -> X, Y in Blender?)
        # Let's check create_rail_with_rabbets call for BOTTOM.
        # extrude_axis='Z'.
        # Profile is in X-Y?
        # parse_svg_path returns (x, y).
        # BOTTOM_RAIL SVG: width=TotalW, height=BoxDepth.
        # So Profile is Top-Down view?
        # Extruded Z (Thickness).
        # So Rail is Flat in XY plane.
        # create_hatch_lid makes thickness in Y.
        # We need thickness in Z.
        # Rotate 90 deg on X?
        bh_obj.rotation_euler = (math.radians(90), 0, 0) 
        
        parts['BOTTOM_HATCH'] = bh_obj
        
        # Cutout in Bottom Rail
        # 1. Through Cut (Opening)
        c1 = create_simple_box("Bottom_Hatch_Cut_Thru", bh_w_m, box_d * 2, bh_h_m, collection) 
        # Wait, create_simple_box dims: (W, Depth, Height).
        # We want W=HatchW, D=HatchH? No.
        # Hatch is aligned X (Width) and Y (Depth of box).
        # So Cutter W = bh_w_m.
        # Cutter D (Blender Y) = bh_h_m.
        # Cutter H (Blender Z) = Thick.
        c1 = create_simple_box("Bottom_Hatch_Cut_Thru", bh_w_m, bh_h_m, stock_thk*4, collection)
        c1.location = (bx, 0, -half_h + stock_thk/2)
        apply_boolean_difference(parts['BOTTOM'], c1, delete_cutter=True)
        
        # 2. Pocket Cut (Shelf)
        # From Outside (Bottom) Face Inwards.
        # Bottom Face Z = -half_h.
        # Pocket Depth = stock/2.
        # Cutter Z = -half_h + stock/4.
        c2 = create_simple_box("Bottom_Hatch_Cut_Pocket", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk/2, collection)
        c2.location = (bx, 0, -half_h + (stock_thk * 0.25))
        apply_boolean_difference(parts['BOTTOM'], c2, delete_cutter=True)

    # 5d. CREATE HATCH (Rear)
    if CONFIG.get('HATCH_ENABLED', False):  # H3 FIX: was == 'True' -> never ran
        print("[5d/8] Creating Rear Hatch Lid...")
        w_pct = float(CONFIG.get('HATCH_WIDTH_PCT', 50.0))
        h_pct = float(CONFIG.get('HATCH_HEIGHT_PCT', 33.0))
        
        h_open_w = (total_w * w_pct / 100.0)
        h_open_h = (total_h * h_pct / 100.0)
        
        # Flange logic
        glue_gap = 0.0005 # approx
        flange_w = (stock_thk / 2.0) - glue_gap
        
        hatch_obj = create_hatch_lid("Box_Hatch_Lid", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        # Specified as "Raise" from bottom Baseline.
        # Baseline = Bottom Frame Inner Edge = -half_h + stock_thk.
        # Raise comes from config (inches).
        raise_in = float(CONFIG.get('HATCH_RAISE_IN', 0.0))
        raise_m = raise_in * 0.0254
        
        # Base Z = Bottom of Hatch.
        # Box Center Z = 0. Range [-H/2, H/2].
        # Bottom of Box = -H/2.
        # Top of Bottom Rail = -H/2 + stock_thk.
        # Hatch Bottom = Top of Rail + Raise.
        base_z = (-half_h + stock_thk) + raise_m
        # Hatch Origin is Center?
        # Logic in `create_hatch_lid` centers it at (0,0,0).
        # So we move Center to:
        # X: 0.
        # Z: Base_Z + (Hatch_Height / 2).
        # Y: Flush with Inside Face of Back Panel?
        # Back Panel Inner Face = half_d.
        # Hatch sits in the hole.
        hatch_y = half_d

        hatch_obj.location = (0, hatch_y, base_z + (h_open_h/2))
        hatch_obj.rotation_euler = (math.pi/2, 0, 0) # Rotate to stand up in X-Z plane
        
        parts['HATCH'] = hatch_obj
        
        # Cutout in Back Panel (Already done by boolean in create_back_panel? No.)
        # v1.12 had separate cutout logic.
        # v1.13 `create_back_panel_with_holes` only does screw holes.
        # We need to Cut the Hatch Opening NOW.
        
        # Cut Opening (Through)
        cutter = create_simple_box("Hatch_Opening_Cut", h_open_w, h_open_h, stock_thk * 3, collection)
        cutter.location = (0, hatch_y, base_z + (h_open_h/2))
        apply_boolean_difference(parts['BACK'], cutter, delete_cutter=True)
        
        # Cut Flange Pocket (Shelf)
        # From Outside Face inwards.
        # Outside Face Y = half_d + stock_thk.
        # Pocket Depth = stock/2.
        # We want to remove the Rear half of the panel thickness.
        pocket_cutter = create_simple_box("Hatch_Pocket_Cut", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, collection)
        # Position: Center aligned. Y depth?
        # Center of cutter at: half_d + stock_thk/2 + stock_thk/4?
        # We want to cut Y range [half_d + stock/2, half_d + stock].
        # Center of that range is half_d + 0.75*stock.
        pocket_cutter.location = (0, half_d + (stock_thk * 0.75), base_z + (h_open_h/2))
        apply_boolean_difference(parts['BACK'], pocket_cutter, delete_cutter=True)

    # 6. POSITION PARTS
    print("[6/8] Positioning parts...")

    # H4 FIX: half_w/half_h/half_d now defined once, near the top of this function.

    # Set origins to geometry center
    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='BOUNDS')
        obj.select_set(False)

    # Get actual horizontal rail width (includes finger protrusions)
    top_rail_width = parts['TOP'].dimensions.x
    finger_tip_x = top_rail_width / 2

    # Position each part
    parts['TOP'].location = (0, 0, half_h - stock_thk/2)
    parts['BOTTOM'].location = (0, 0, -half_h + stock_thk/2)
    parts['LEFT'].location = (-finger_tip_x + stock_thk/2, 0, 0)
    parts['RIGHT'].location = (finger_tip_x - stock_thk/2, 0, 0)
    parts['FRONT'].location = (0, -half_d - stock_thk/2, 0)
    parts['BACK'].location = (0, half_d + stock_thk/2, 0)

    # 7. APPLY TRANSFORMS AND MATERIALS
    print("[7/8] Applying transforms and materials...")

    # Apply transforms first
    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
        obj.select_set(False)

    # Define end grain axes for each part (after transforms applied)
    end_grain_config = {{
        'TOP': ['X'],           # End grain on left/right (finger sides)
        'BOTTOM': ['X'],        # End grain on left/right (finger sides)
        'LEFT': ['Z'],          # After rotation, end grain points up/down
        'RIGHT': ['Z'],         # After rotation, end grain points up/down
        'FRONT': ['X', 'Z'],    # End grain on all 4 edges
        'BACK': ['X', 'Z'],     # End grain on all 4 edges
    }}

    for key, obj in parts.items():
        apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_config.get(key, []))

    # Parent all parts to a main Empty for unified movement
    print("[8a/8] Parenting parts to root object...")
    root_empty = bpy.data.objects.new("Box_Box_Root", None)
    collection.objects.link(root_empty)
    root_empty.location = (0, 0, 0)
    root_empty.empty_display_type = 'CUBE'
    root_empty.empty_display_size = 0.5
    
    for key, obj in parts.items():
        obj.parent = root_empty
        obj.matrix_parent_inverse = root_empty.matrix_world.inverted()

    # 8. ADD LIGHTING
    print("[8/8] Setting up lighting...")

    # Area light per JLS specifications
    light_data = bpy.data.lights.new(name="Area_Light", type='AREA')
    light_data.color = (1.0, 1.0, 1.0)  # #FFFFFF
    light_data.energy = 5.0             # Power: 5 (User Request)
    light_data.shape = 'SQUARE'         # Shape: square
    light_data.size = 300 * 0.0254      # Size: 300 (convert inches to meters)
    light_data.spread = math.radians(180)  # Spread: 180 degrees

    # Set exposure on the scene/view layer
    # M6 NOTE: USER_SPECIFICATIONS SPEC-009 specifies exposure 2.5; this code uses 4.0.
    # Left at 4.0 (visual choice) rather than silently changing brightness — reconcile with
    # SPEC-009 (update the spec, or set this to 2.5) per your preference.
    bpy.context.scene.view_settings.exposure = 4.0

    light_obj = bpy.data.objects.new("Area_Light", light_data)
    collection.objects.link(light_obj)

    # Location: -90", -20", -80" (convert to meters)
    light_obj.location = (-90 * 0.0254, -20 * 0.0254, -80 * 0.0254)
    # Rotation: 0, 208, 0 degrees
    light_obj.rotation_euler = (0, math.radians(208), 0)

    # Set viewport shading to Material Preview
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            for space in area.spaces:
                if space.type == 'VIEW_3D':
                    space.shading.type = 'MATERIAL'
                    space.clip_start = 0.001  # M6 FIX: SPEC-008 requires <= 0.001m (was 0.01, 10x too far)
                    space.clip_end = 1000.0
                    break
            break

    # Frame all objects
    for area in bpy.context.screen.areas:
        if area.type == 'VIEW_3D':
            region = next((r for r in area.regions if r.type == 'WINDOW'), None)
            if region:
                override = bpy.context.copy()
                override['area'] = area
                override['region'] = region
                with bpy.context.temp_override(**override):
                    bpy.ops.view3d.view_all(center=True)
                break

    # Switch to JLS Workspace if it exists
    if "JLS Workspace" in bpy.data.workspaces:
        bpy.context.window.workspace = bpy.data.workspaces["JLS Workspace"]
        print("  - Switched to JLS Workspace")
    else:
        print("  - JLS Workspace not found, using current workspace")

    print("\\n" + "=" * 60)
    print("ASSEMBLY COMPLETE!")
    print("=" * 60)
    print(f"\\nDimensions:")
    print(f"  Total Width:  {{CONFIG['TOTAL_WIDTH_IN']:.2f}} inches")
    print(f"  Total Height: {{CONFIG['TOTAL_HEIGHT_IN']:.2f}} inches")
    print(f"  Box Depth:    {{CONFIG['BOX_DEPTH_IN']:.2f}} inches")
    print(f"  Stock:        {{CONFIG['STOCK_THICKNESS_IN']:.4f}} inches (15mm)")
    print(f"\\nBoolean Cuts Applied:")
    print(f"  - Front Bezel: Window cutout (with cap faces removed)")
    print(f"  - Back Panel:  {{len(BACK_PANEL_HOLES)}} screw holes (with cap faces removed)")
    print(f"\\nMaterials:")
    print(f"  Wide face: #E2CBAD")
    print(f"  End grain: #C0AD93")
    print(f"\\nParts created: {{len(parts)}}")
    
    # FINAL FIX: Ensure all objects have their Origin at Geometric Center
    # This fixes the "Gizmo Rotation" issue if SVG import caused offsets.
    print("[Finalizing] Centering Origins...")
    for obj in collection.objects:
        if obj.type == 'MESH':
            bpy.context.view_layer.objects.active = obj
            obj.select_set(True)
            bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='BOUNDS')
            obj.select_set(False)
            
    # Also ensure Root is at World Origin (it is, but good to be sure)
    root_empty.location = (0, 0, 0)
    
    print("\\nTIP: Press Numpad 0 for camera view, or use the viewport controls to orbit.")

# ==============================================================================
# RUN
# ==============================================================================
if __name__ == "__main__":
    create_shadowbox_assembly()
'''

    return script


def generate_trivision_script(version, config, rail_paths, geom_front, geom_back, collection_name="OUTSIDE FRAME"):
    """
    Generate the 'OPEN ME IN TRIVISION' script.
    Same as Blender script but:
    - Collection: BOX GENERATOR
    - No lighting/world/view/unit changes
    """
    
    # Calculate dimensions from config
    total_width_in = convert_to_inches(config['TOTAL_WIDTH'])
    total_height_in = convert_to_inches(config['TOTAL_HEIGHT'])
    box_depth_in = convert_to_inches(config['BOX_DEPTH'])
    stock_thk_in = convert_to_inches(config['STOCK_THICKNESS'])
    
    # Window dimensions (retrieved from config or defaulted)
    window_width_in = config.get('WINDOW_WIDTH_IN', total_width_in - 3.0)
    window_height_in = config.get('WINDOW_HEIGHT_IN', total_height_in - 3.0)
    
    # Rabbet dimensions
    front_rabbet_w_in = config.get('FRONT_RABBET_WIDTH', 0.3)
    front_rabbet_d_in = config.get('FRONT_RABBET_DEPTH', 0.3)
    back_rabbet_w_in = config.get('BACK_RABBET_WIDTH', 0.3)
    back_rabbet_d_in = config.get('BACK_RABBET_DEPTH', 0.3)
    
    # Extract hole data
    back_holes = geom_back.get('holes', [])
    back_hole_r_in = geom_back.get('hole_r', 0.1)
    back_rim_width_in = geom_back.get('rim_width', 0.3)
    
    # Extract front bezel rim width
    front_rim_width_in = config.get('FRONT_RIM_WIDTH_IN', 0.3)
    if 'FRONT_RIM_WIDTH_M' in config:
         front_rim_width_in = config['FRONT_RIM_WIDTH_M'] / 0.0254

    # Convert to meters for Blender
    total_width_m = total_width_in * 0.0254
    total_height_m = total_height_in * 0.0254
    box_depth_m = box_depth_in * 0.0254
    stock_thk_m = stock_thk_in * 0.0254
    
    window_width_m = window_width_in * 0.0254
    window_height_m = window_height_in * 0.0254
    
    front_rabbet_w_m = front_rabbet_w_in * 0.0254
    front_rabbet_d_m = front_rabbet_d_in * 0.0254
    back_rabbet_w_m = back_rabbet_w_in * 0.0254
    back_rabbet_d_m = back_rabbet_d_in * 0.0254
    
    back_hole_r_m = back_hole_r_in * 0.0254
    back_rim_width_m = back_rim_width_in * 0.0254
    front_rim_width_m = front_rim_width_in * 0.0254
    
    # Convert hole positions to meters (subtract margin first, then convert)
    holes_m = []
    for hx, hy in back_holes:
        hx_in = hx - MARGIN_INCHES
        hy_in = hy - MARGIN_INCHES
        holes_m.append((hx_in * 0.0254, hy_in * 0.0254))

    script = f'''#!/usr/bin/env python3
"""
OPEN ME IN TRIVISION - Shadowbox Assembly v{version}
===========================================================
Generated by CNC Generator - Carbide-Optimized v{version}

This script imports the generated box into an existing Blender scene.
It creates a collection 'BOX GENERATOR' and places all parts there.
It does NOT alter scene lighting, units, or world settings.
"""

import bpy
import bmesh
import re
from mathutils import Vector, Euler
import math

# ==============================================================================
# CONFIGURATION
# ==============================================================================
CONFIG = {{
    'TOTAL_WIDTH_IN': {total_width_in:.4f},
    'TOTAL_HEIGHT_IN': {total_height_in:.4f},
    'BOX_DEPTH_IN': {box_depth_in:.4f},
    'STOCK_THICKNESS_IN': {stock_thk_in:.4f},
    'STOCK_THICKNESS_M': {stock_thk_m:.6f},
    'TOTAL_WIDTH_M': {total_width_m:.6f},
    'TOTAL_HEIGHT_M': {total_height_m:.6f},
    'BOX_DEPTH_M': {box_depth_m:.6f},
    'WINDOW_WIDTH_M': {window_width_m:.6f},
    'WINDOW_HEIGHT_M': {window_height_m:.6f},
    'FRONT_RABBET_WIDTH_M': {front_rabbet_w_m:.6f},
    'FRONT_RABBET_DEPTH_M': {front_rabbet_d_m:.6f},
    'BACK_RABBET_WIDTH_M': {back_rabbet_w_m:.6f},
    'BACK_RABBET_DEPTH_M': {back_rabbet_d_m:.6f},
    'BACK_HOLE_RADIUS_M': {back_hole_r_m:.6f},
    'BACK_RIM_WIDTH_M': {back_rim_width_m:.6f},
    'FRONT_RIM_WIDTH_M': {front_rim_width_m:.6f},
}}

# Back panel hole positions (in meters)
BACK_PANEL_HOLES = {holes_m}

# SVG MARGIN used in path generation (2 inches)
MARGIN_IN = 2.0

# Plywood colors
COLOR_WIDE_FACE = (0xE2/255, 0xCB/255, 0xAD/255, 1.0)
COLOR_END_GRAIN = (0xC0/255, 0xAD/255, 0x93/255, 1.0)

# ==============================================================================
# SVG PATH DATA
# ==============================================================================
SVG_PATHS = {{
    'TOP_RAIL': """{rail_paths.get('TOP', 'M 0 0 Z')}""",
    'BOTTOM_RAIL': """{rail_paths.get('BOTTOM', 'M 0 0 Z')}""",
    'LEFT_RAIL': """{rail_paths.get('LEFT', 'M 0 0 Z')}""",
    'RIGHT_RAIL': """{rail_paths.get('RIGHT', 'M 0 0 Z')}""",
}}

# ==============================================================================
# HELPER FUNCTIONS (Duplicated for standalone capability)
# ==============================================================================

def parse_svg_path(path_d, margin_offset=2.0):
    vertices = []
    commands = re.findall(r'([MLZ])\\s*([\\d.\\-\\s]*)', path_d)
    for cmd, coords_str in commands:
        if cmd == 'Z': continue
        coords = coords_str.strip().split()
        if len(coords) >= 2:
            x_in = float(coords[0]) - margin_offset
            y_in = float(coords[1]) - margin_offset
            x_m = x_in * 0.0254
            y_m = y_in * 0.0254
            vertices.append((x_m, y_m))
    return vertices

def create_plywood_materials():
    # Check if materials already exist to avoid duplicates or use them
    mat_wide = bpy.data.materials.get("Plywood_Wide_Face")
    if not mat_wide:
        mat_wide = bpy.data.materials.new(name="Plywood_Wide_Face")
        mat_wide.use_nodes = True
        nodes = mat_wide.node_tree.nodes
        nodes.clear()
        output = nodes.new('ShaderNodeOutputMaterial')
        principled = nodes.new('ShaderNodeBsdfPrincipled')
        principled.inputs['Base Color'].default_value = COLOR_WIDE_FACE
        principled.inputs['Roughness'].default_value = 0.6
        mat_wide.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    mat_end = bpy.data.materials.get("Plywood_End_Grain")
    if not mat_end:
        mat_end = bpy.data.materials.new(name="Plywood_End_Grain")
        mat_end.use_nodes = True
        nodes = mat_end.node_tree.nodes
        nodes.clear()
        output = nodes.new('ShaderNodeOutputMaterial')
        principled = nodes.new('ShaderNodeBsdfPrincipled')
        principled.inputs['Base Color'].default_value = COLOR_END_GRAIN
        principled.inputs['Roughness'].default_value = 0.7
        mat_end.node_tree.links.new(principled.outputs['BSDF'], output.inputs['Surface'])

    return mat_wide, mat_end

def get_face_dominant_axis(face_normal):
    abs_normal = [abs(face_normal.x), abs(face_normal.y), abs(face_normal.z)]
    max_idx = abs_normal.index(max(abs_normal))
    return ['X', 'Y', 'Z'][max_idx]

def apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_axes):
    if obj.type != 'MESH': return
    if mat_wide.name not in obj.data.materials: obj.data.materials.append(mat_wide)
    if mat_end.name not in obj.data.materials: obj.data.materials.append(mat_end)
    # Ensure correct indices
    wide_idx = obj.data.materials.find(mat_wide.name)
    end_idx = obj.data.materials.find(mat_end.name)
    
    bm = bmesh.new()
    bm.from_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    for face in bm.faces:
        normal_world = obj.matrix_world.to_3x3() @ face.normal
        dominant_axis = get_face_dominant_axis(normal_world)
        if dominant_axis in end_grain_axes:
            face.material_index = end_idx
        else:
            face.material_index = wide_idx
    bm.to_mesh(obj.data)
    bm.free()
    obj.data.update()

def create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis='Z'):
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    # Link to collection immediately
    collection.objects.link(obj)
    bm = bmesh.new()
    bottom_verts = []
    for v in vertices:
        if extrude_axis == 'Z': vert = bm.verts.new((v[0], v[1], 0))
        elif extrude_axis == 'Y': vert = bm.verts.new((v[0], 0, v[1]))
        elif extrude_axis == 'X': vert = bm.verts.new((0, v[0], v[1]))
        bottom_verts.append(vert)
    bm.verts.ensure_lookup_table()
    if len(bottom_verts) >= 3:
        try: bm.faces.new(bottom_verts)
        except: pass
    if extrude_axis == 'Z': extrude_vec = Vector((0, 0, thickness_m))
    elif extrude_axis == 'Y': extrude_vec = Vector((0, thickness_m, 0))
    elif extrude_axis == 'X': extrude_vec = Vector((thickness_m, 0, 0))
    ret = bmesh.ops.extrude_face_region(bm, geom=bm.faces[:])
    verts = [e for e in ret['geom'] if isinstance(e, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, verts=verts, vec=extrude_vec)
    bm.to_mesh(mesh)
    bm.free()
    mesh.update()
    return obj

def create_simple_box(name, width_m, height_m, depth_m, collection):
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    bm = bmesh.new()
    bmesh.ops.create_cube(bm, size=1.0)
    bm.to_mesh(mesh)
    bm.free()
    obj.dimensions = (width_m, depth_m, height_m)
    return obj

def create_cylinder_cutter(name, radius_m, depth_m, collection, segments=32):
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    bm = bmesh.new()
    bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=segments, radius1=radius_m, radius2=radius_m, depth=depth_m)
    bm.to_mesh(mesh)
    bm.free()
    return obj

def apply_boolean_difference(target_obj, cutter_obj, delete_cutter=True):
    success = False
    try:
        bpy.context.view_layer.objects.active = cutter_obj
        cutter_obj.select_set(True)
        bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
        cutter_obj.select_set(False)
        # Check if already has boolean with same name
        if target_obj.modifiers.get("Boolean_Cut"):
            target_obj.modifiers.remove(target_obj.modifiers["Boolean_Cut"])
        bool_mod = target_obj.modifiers.new(name="Boolean_Cut", type='BOOLEAN')
        bool_mod.operation = 'DIFFERENCE'
        bool_mod.object = cutter_obj
        bool_mod.solver = 'EXACT'
        bpy.context.view_layer.objects.active = target_obj
        target_obj.select_set(True)
        bpy.ops.object.modifier_apply(modifier=bool_mod.name)
        target_obj.select_set(False)
        success = True
    except Exception as e:
        print(f"Warning: Boolean failed {{e}}")
        if "Boolean_Cut" in target_obj.modifiers: target_obj.modifiers.remove(target_obj.modifiers["Boolean_Cut"])
    if delete_cutter:
        try: bpy.data.objects.remove(cutter_obj, do_unlink=True)
        except: pass
    return success

def remove_inner_cap_faces(obj, inner_bound_x, inner_bound_z):
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    faces_to_delete = []
    for face in bm.faces:
        all_inner = True
        for vert in face.verts:
            if abs(vert.co.x) > inner_bound_x + 0.001 or abs(vert.co.z) > inner_bound_z + 0.001:
                all_inner = False
                break
        if all_inner: faces_to_delete.append(face)
    for face in faces_to_delete: bm.faces.remove(face)
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    return len(faces_to_delete)

def remove_hole_cap_faces(obj, hole_positions, y_front, y_back):
    bpy.context.view_layer.objects.active = obj
    bpy.ops.object.mode_set(mode='EDIT')
    bm = bmesh.from_edit_mesh(obj.data)
    bm.faces.ensure_lookup_table()
    faces_to_delete = []
    for face in bm.faces:
        centroid = face.calc_center_median()
        y_vals = [v.co.y for v in face.verts]
        if all(abs(y - y_front) < 0.001 for y in y_vals) or all(abs(y - y_back) < 0.001 for y in y_vals):
            for hx, hz in hole_positions:
                dist = ((centroid.x - hx)**2 + (centroid.z - hz)**2)**0.5
                if dist < 0.01:
                    faces_to_delete.append(face)
                    break
    for face in faces_to_delete: bm.faces.remove(face)
    bmesh.update_edit_mesh(obj.data)
    bpy.ops.object.mode_set(mode='OBJECT')
    return len(faces_to_delete)

def create_front_bezel_with_window(name, width_m, height_m, thickness_m, window_w_m, window_h_m, rim_width_m, collection):
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    mesh = obj.data
    bezel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    bezel_center_y = (bezel_y_min + bezel_y_max) / 2
    window_w = window_w_m
    window_h = window_h_m
    if window_w > 0 and window_h > 0:
        cutter_mesh = bpy.data.meshes.new(name + "_window_cutter_mesh")
        window_cutter = bpy.data.objects.new(name + "_window_cutter", cutter_mesh)
        collection.objects.link(window_cutter)
        bm = bmesh.new()
        hw = window_w / 2
        hd = thickness_m * 1.5
        hh = window_h / 2
        verts = [bm.verts.new((-hw, -hd, -hh)), bm.verts.new(( hw, -hd, -hh)), bm.verts.new(( hw,  hd, -hh)), bm.verts.new((-hw,  hd, -hh)),
                 bm.verts.new((-hw, -hd,  hh)), bm.verts.new(( hw, -hd,  hh)), bm.verts.new(( hw,  hd,  hh)), bm.verts.new((-hw,  hd,  hh))]
        bm.faces.new([verts[0], verts[1], verts[2], verts[3]])
        bm.faces.new([verts[4], verts[7], verts[6], verts[5]])
        bm.faces.new([verts[0], verts[4], verts[5], verts[1]])
        bm.faces.new([verts[2], verts[6], verts[7], verts[3]])
        bm.faces.new([verts[0], verts[3], verts[7], verts[4]])
        bm.faces.new([verts[1], verts[5], verts[6], verts[2]])
        bm.to_mesh(cutter_mesh)
        bm.free()
        window_cutter.location = (0, bezel_center_y, 0)
        apply_boolean_difference(obj, window_cutter, delete_cutter=True)
        # removed v1.13: remove_inner_cap_faces(obj, window_w/2, window_w/2) 
        # (Boolean difference works correctly, manual removal was deleting walls)
    return obj

def create_back_panel_with_holes(name, width_m, height_m, thickness_m, hole_positions, hole_radius_m, rim_width_m, collection):
    obj = create_simple_box(name, width_m, height_m, thickness_m, collection)
    bpy.context.view_layer.objects.active = obj
    obj.select_set(True)
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True)
    obj.select_set(False)
    mesh = obj.data
    panel_y_min = min((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_y_max = max((obj.matrix_world @ v.co).y for v in mesh.vertices)
    panel_center_y = (panel_y_min + panel_y_max) / 2
    centered_hole_positions = []
    if hole_positions and hole_radius_m > 0:
        for i, (hx, hy) in enumerate(hole_positions):
            hole_cutter = create_cylinder_cutter(f"{{name}}_hole_{{i}}", hole_radius_m, thickness_m * 3, collection, segments=16)
            hole_cutter.rotation_euler = (math.pi/2, 0, 0)
            hole_x = hx - width_m/2
            hole_z = hy - height_m/2
            hole_cutter.location = (hole_x, panel_center_y, hole_z)
            centered_hole_positions.append((hole_x, hole_z))
            bpy.context.view_layer.objects.active = hole_cutter
            hole_cutter.select_set(True)
            bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
            hole_cutter.select_set(False)
            apply_boolean_difference(obj, hole_cutter, delete_cutter=True)
        # removed v1.13: remove_hole_cap_faces(...)
    return obj

def create_rail_with_rabbets(name, vertices, thickness_m, collection, fr_w, fr_d, br_w, br_d, length_m, depth_m, extrude_axis='Z'):
    if len(vertices) >= 3: return create_mesh_from_profile(name, vertices, thickness_m, collection, extrude_axis)
    else: return create_simple_box(name, length_m, thickness_m, depth_m, collection)

def create_french_cleat(name, width_m, height_m, thickness_m, collection, is_wall_part=False):
    # Profile: Rectangle with 45 deg bevel on top/bottom mating edge.
    # Wall Part: Bevel points UP and AWAY from wall? 
    # Standard French Cleat:
    # Wall piece: Screw to wall. Top edge is beveled (low against wall, high away).
    # Box piece: Screw to box. Bottom edge is beveled (low away, high against box).
    # Box piece "hooks" over Wall piece.
    
    # Let's model a simple prism.
    # Profile in X-Y plane (Side View), extruded in X (Width).
    
    # Vertices (Z-Y view):
    # Wall Cleat: 
    # (0,0) -> (Thk, 0) -> (Thk, H-Thk) -> (0, H) -> Close.
    # Wait, Bevel is 45 deg.
    # If Thk is small, bevel is full thickness? Usually.
    
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    
    bm = bmesh.new()
    
    # Profile (looking from Side/Right -> Y-Z plane)
    # Origin at Bottom-Back corner.
    # Wall Cleat (Mounted on Wall): Back is at Y=0 (Wall).
    # Bottom: (0,0). Top Back: (0, H).
    # Top Front: (Thk, H-Thk) [Bevel Tip]
    # Bot Front: (Thk, 0).
    
    # Box Cleat (Mounted on Box): Back is at Y=0 (Box).
    # Top: (0, H) -> (Thk, H).
    # Bot Front: (Thk, Thk). Bot Back: (0, 0).
    # Mates with Wall Cleat.
    
    # NOTE: Our Assembly has explicit positions.
    # Let's make a generic Box: W, H, Thk.
    # Then apply a chamfer or just simple geometry.
    
    # Simple Extrusion along X (Width).
    # Profile in Y-Z.
    
    if is_wall_part:
        # Wall Cleat Profile
        # Back is Z-axis line.
        # Bevel at Top.
        verts = [
            (0, 0), # Bot Back
            (thickness_m, 0), # Bot Front
            (thickness_m, height_m - thickness_m), # Top Front (Bevel Start)
            (0, height_m) # Top Back
        ]
    else:
        # Box Cleat Profile
        # Back is Z-axis line.
        # Bevel at Bottom.
        verts = [
            (0, 0), # Bot Back (Tip)
            (thickness_m, thickness_m), # Bot Front (Bevel End)
            (thickness_m, height_m), # Top Front
            (0, height_m) # Top Back
        ]
        
    # Extrude along X (Width)
    # Center Width?
    # Let's create verts then extrude.
    
    profile_verts = []
    # Shift so Width is Centered on X=0?
    hw = width_m / 2.0
    
    for v_yz in verts:
        # Left Side (X = -hw)
        profile_verts.append(bm.verts.new((-hw, v_yz[0], v_yz[1]))) # Map Y->Y, Z->Z? No, our Profile was Y,Z? 
        # Actually in coords: (X, Y, Z)
        # Profile defined in Y(Depth), Z(Height).
        
    bm.verts.ensure_lookup_table()
    # Make Face
    try: bm.faces.new(profile_verts)
    except: pass
    
    # Extrude to X = +hw
    # Normal extrude vector = (width_m, 0, 0)
    ret = bmesh.ops.extrude_face_region(bm, geom=bm.faces[:])
    verts_ext = [e for e in ret['geom'] if isinstance(e, bmesh.types.BMVert)]
    bmesh.ops.translate(bm, verts=verts_ext, vec=(width_m, 0, 0)) # Wait, if we started at -hw, we move full Width.
    
    # Wait, my logic: started at -hw. Moving +width gets to +hw. Correct.
    
    bm.to_mesh(mesh)
    bm.free()
    
    return obj

def create_hatch_lid(name, w, h, thk, flange_w, collection):
    # Complex Lid:
    # Outer Rect (w, h)
    # Boolean cutout (Rabbet) on edges to form step.
    # Simpler: Create Base (Opening size) + Flange (Lid size).
    # Standard Hatch: Lid sits ON TOP of shelf? Or Flush?
    # Usually Flush. So it's Stepped.
    # Top Part: Full W/H, partial thickness.
    # Bot Part: Opening W/H, partial thickness.
    
    mesh = bpy.data.meshes.new(name + "_mesh")
    obj = bpy.data.objects.new(name, mesh)
    collection.objects.link(obj)
    
    bm = bmesh.new()
    
    # Top Plate (Flange)
    # Dimensions: w, h. Thk/2.
    bmesh.ops.create_cube(bm, size=1.0)
    bmesh.ops.scale(bm, vec=(w, thk/2, h), verts=bm.verts) # Y-up thickness?
    # Check orientation. Assembly: Back Panel is in X-Z plane (Vertical). Thickness Y.
    # So Lid Thickness is Y.
    # Top Plate Y center = thk/4.
    bmesh.ops.translate(bm, vec=(0, thk/4, 0), verts=bm.verts)
    
    # Bottom Plate (Insert)
    # Dims: w - 2*flange, h - 2*flange.
    bm2 = bmesh.new()
    bmesh.ops.create_cube(bm2, size=1.0)
    bmesh.ops.scale(bm2, vec=(w - 2*flange_w, thk/2, h - 2*flange_w), verts=bm2.verts)
    bmesh.ops.translate(bm2, vec=(0, -thk/4, 0), verts=bm2.verts)
    
    # Merge
    bm.from_mesh(bm2.to_mesh()) # Simple merge
    bm2.free()
    
    bm.to_mesh(mesh)
    bm.free()
    return obj

def create_shadowbox_assembly():
    print("=" * 60)
    print("Creating Shadowbox in TRIVISION Mode")
    print("Collection: {collection_name}")
    print("=" * 60)

    # Create collection "{collection_name}" (no scene lighting/unit changes)
    collection_name = "{collection_name}"
    collection = bpy.data.collections.get(collection_name)
    if not collection:
        collection = bpy.data.collections.new(collection_name)
        bpy.context.scene.collection.children.link(collection)
    
    # Make it active
    layer_collection = bpy.context.view_layer.layer_collection.children.get(collection_name)
    if layer_collection:
        bpy.context.view_layer.active_layer_collection = layer_collection

    # Create Materials (Reusing if exist)
    mat_wide, mat_end = create_plywood_materials()

    # Create Parts
    stock_thk = CONFIG['STOCK_THICKNESS_M']
    total_w = CONFIG['TOTAL_WIDTH_M']
    total_h = CONFIG['TOTAL_HEIGHT_M']
    box_d = CONFIG['BOX_DEPTH_M']

    parts = {{}}

    # TOP
    top_verts = parse_svg_path(SVG_PATHS['TOP_RAIL'])
    parts['TOP'] = create_rail_with_rabbets("OUTSIDE_TOP_RAIL", top_verts, stock_thk, collection, 0,0,0,0, total_w, box_d, 'Z')

    # BOTTOM
    bot_verts = parse_svg_path(SVG_PATHS['BOTTOM_RAIL'])
    parts['BOTTOM'] = create_rail_with_rabbets("OUTSIDE_BOTTOM_RAIL", bot_verts, stock_thk, collection, 0,0,0,0, total_w, box_d, 'Z')

    # LEFT
    left_verts = parse_svg_path(SVG_PATHS['LEFT_RAIL'])
    parts['LEFT'] = create_rail_with_rabbets("OUTSIDE_LEFT_RAIL", left_verts, stock_thk, collection, 0,0,0,0, total_h, box_d, 'Z')
    parts['LEFT'].rotation_euler = (0, math.radians(90), 0)

    # RIGHT
    right_verts = parse_svg_path(SVG_PATHS['RIGHT_RAIL'])
    parts['RIGHT'] = create_rail_with_rabbets("OUTSIDE_RIGHT_RAIL", right_verts, stock_thk, collection, 0,0,0,0, total_h, box_d, 'Z')
    parts['RIGHT'].rotation_euler = (0, math.radians(-90), 0)

    # FRONT
    parts['FRONT'] = create_front_bezel_with_window("OUTSIDE_FRONT_BEZEL", total_w, total_h, stock_thk, CONFIG['WINDOW_WIDTH_M'], CONFIG['WINDOW_HEIGHT_M'], CONFIG['FRONT_RIM_WIDTH_M'], collection)

    # BACK
    parts['BACK'] = create_back_panel_with_holes("OUTSIDE_BACK_PANEL", total_w, total_h, stock_thk, BACK_PANEL_HOLES, CONFIG['BACK_HOLE_RADIUS_M'], CONFIG['BACK_RIM_WIDTH_M'], collection)

    # --- v1.10 EXTENSIONS (Cleats + Hatch) ---
    
    # Cleats
    cleat_obj_box = None
    if CONFIG.get('CLEATS_ENABLED', True):
        cw = min(total_w * 0.80, 48.0 * 0.0254) # Match generator logic (inches converted to m already? No generator does it in in)
        # Recalc precisely:
        cw = min(CONFIG['TOTAL_WIDTH_IN'] * 0.80, 48.0) * 0.0254
        ch = 4.0 * 0.0254
        
        # 1. Box Cleat
        cleat_obj_box = create_french_cleat("OUTSIDE_CLEAT_BOX", cw, ch, stock_thk, collection, is_wall_part=False)
        
        # Position:
        # Attached to BACK of Back Panel? Or embedded?
        # Usually screwed to the Back Face of Back Panel.
        # Back Panel Center: (0, box_d/2 + stock/2, 0).
        # Back Face of Back Panel is at Y = box_d/2 + stock.
        # So Cleat Back is at Y = box_d/2 + stock.
        # Height: 1/3 from Top.
        # Top of Frame = +total_h/2.
        # Cleat Center Y (Vertical Z) = (total_h/2) - (total_h/3). = total_h/6.
        # Wait, user said "centered at 1/3... from top".
        # So Z = (TotalH/2) - (TotalH/3).
        
        cleat_z = (total_h / 2.0) - (total_h / 3.0)
        cleat_y = (box_d / 2.0) + stock_thk
        
        # Create Cleat Object
        cleat_obj_box.location = (0, cleat_y, cleat_z)
        
        # Mounting Holes (Boolean)
        # "5%, 33%, 66%, 95%"
        # Create Cylinder Cutters.
        hole_pcts = [0.05, 0.33, 0.66, 0.95]
        # X starts at -cw/2.
        
        for i, pct in enumerate(hole_pcts):
            h_x_local = (-cw/2.0) + (pct * cw)
            # Create Cutter (local to cleat?)
            # Or use global cutter on both Cleat and Back Panel?
            
            # Cutter for Cleat (Countersunk)
            # Simple hole for viz
            cutter = create_cylinder_cutter(f"Cleat_Hole_{{i}}", 0.005, stock_thk*4, collection) # 5mm radius?
            cutter.rotation_euler = (math.pi/2, 0, 0)
            cutter.location = (h_x_local, 0, 0) # Local to Cleat?
            # Parenting/Transform issue if we use boolean.
            # Easiest: Position cutter globally match cleat.
            cutter.location = (h_x_local, cleat_y, cleat_z)
            
            # Apply to Cleat
            apply_boolean_difference(cleat_obj_box, cutter, delete_cutter=False)
            
            # Apply to Back Panel (Through Hole)
            # Back Panel Object: parts['BACK']
            # Reuse cutter? Yes.
            apply_boolean_difference(parts['BACK'], cutter, delete_cutter=True)

        parts['CLEAT_BOX'] = cleat_obj_box
        
        # 2. Wall Cleat (Mating)
        cleat_obj_wall = create_french_cleat("OUTSIDE_CLEAT_WALL", cw, ch, stock_thk, collection, is_wall_part=True)
        # Mated Position:
        # Wall Cleat slides UNDER/BEHIND Box Cleat.
        # It engages.
        # Geometry: Box Cleat bevel faces IN/Down. Wall Cleat bevel faces OUT/Up.
        # They overlap in Thickness? No, they stack.
        # Wall Cleat is closer to Wall (further +Y).
        # Box Cleat Y = cleat_y.
        # Wall Cleat Y = cleat_y + stock_thk? No, that would be floating.
        # They interlock. 
        # For simple visual: Stack them?
        # Let's put Wall Cleat at Y = cleat_y + stock_thk (simulating wall surface).
        # Z should match (engaged).
        cleat_obj_wall.location = (0, cleat_y + stock_thk, cleat_z)
        parts['CLEAT_WALL'] = cleat_obj_wall
        
    # 5c. CREATE BOTTOM ACCESS HATCH (v1.25)
    if CONFIG.get('BOTTOM_HATCH_ENABLED', False):
        print("[5c/8] Creating Bottom Access Hatch...")
        # Dims from Config (mm -> in -> m)
        bh_w_m = float(CONFIG.get('BOTTOM_HATCH_WIDTH', 0)) * 0.001 
        bh_h_m = float(CONFIG.get('BOTTOM_HATCH_HEIGHT', 0)) * 0.001
        bh_x_pct = float(CONFIG.get('BOTTOM_HATCH_X_PCT', 50.0))
        
        # Flange logic
        glue_gap = 0.0005 
        flange_w = (stock_thk / 2.0) - glue_gap
        if flange_w < 0.001: flange_w = 0.001

        # Create Hatch Lid Object
        bh_obj = create_hatch_lid("OUTSIDE_BOTTOM_HATCH_LID", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        inner_w = total_w - (2 * stock_thk)
        bx = (-(total_w/2) + stock_thk) + (bh_x_pct / 100.0 * inner_w)
        
        # Rotation (Flat on Bottom)
        bh_obj.rotation_euler = (math.radians(90), 0, 0)
        
        # Location (Centered in Depth Y=0, Bottom of Box Z)
        # Bottom Rail Z = -half_h + stock_thk/2.
        bh_obj.location = (bx, 0, -half_h + stock_thk/2)
        
        parts['BOTTOM_HATCH'] = bh_obj
        
        # Cutout in Bottom Rail
        # 1. Through Cut
        c1 = create_simple_box("Bottom_Hatch_Cut_Thru", bh_w_m, bh_h_m, stock_thk*4, collection)
        c1.location = (bx, 0, -half_h + stock_thk/2)
        apply_boolean_difference(parts['BOTTOM'], c1, delete_cutter=True)
        
        # 2. Pocket Cut (Shelf)
        # From Outside (Bottom) Face Inwards.
        # Bottom Face Z = -half_h.
        # Pocket Depth = stock/2.
        # Cutter Z = -half_h + stock/4.
        c2 = create_simple_box("Bottom_Hatch_Cut_Pocket", bh_w_m + 2*flange_w, bh_h_m + 2*flange_w, stock_thk/2, collection)
        c2.location = (bx, 0, -half_h + (stock_thk * 0.25))
        apply_boolean_difference(parts['BOTTOM'], c2, delete_cutter=True)

    # Hatch Lid (Rear)
    if CONFIG.get('HATCH_ENABLED', False):
        # Create Hatch Lid
        # Dims
        h_w_pct = CONFIG.get('HATCH_WIDTH_PCT', 50.0) / 100.0
        h_h_pct = CONFIG.get('HATCH_HEIGHT_PCT', 33.0) / 100.0
        h_open_w = total_w * h_w_pct
        h_open_h = total_h * h_h_pct
        
        glue_gap = 0.0005 # approx
        flange_w = (stock_thk / 2.0) - glue_gap
        
        hatch_obj = create_hatch_lid("OUTSIDE_HATCH_LID", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, flange_w, collection)
        
        # Position
        # Position: Center X, Back Face Y, Z determined by Raise
        # Base Z = Bottom of Box (-H/2) + Stock + Raise
        base_z = (-total_h / 2.0) + stock_thk + raise_m
        
        # Hatch Center Z = Base Z + (Hatch Open H / 2) + Flange?
        # Hatch Object Origin is Center.
        # Ideally match the cutout.
        # The Cutout Center Z = Base Z + (h_open_h / 2).
        hatch_z = base_z + (h_open_h / 2.0)
        
        hatch_y = (box_d / 2.0) # Flush with Inside Face?
        # Back Panel: Thick Z (Y in global). Center Y = box_d/2 + stock/2.
        # Inside Face = box_d/2.
        # Hatch usually flush with inside?
        # Yes.
        
        hatch_obj.location = (0, hatch_y, hatch_z)
        # Check orientation: create_hatch_lid made it flat (X-Z)? scaled Y=Thk.
        # Yes. 
        
        parts['HATCH'] = hatch_obj
        
        # Cutout in Back Panel
        # We need to cut the Back Panel to accept the Hatch.
        # Opening (Through) + Shelf (Pocket).
        # Let's just cut the Opening for visual simplicity?
        # Or proper stepped boolean?
        # Create Stepped Cutter.
        # Cutter 1: Through (Inner Size).
        c1 = create_simple_box("Hatch_Cut_Thru", h_open_w, h_open_h, stock_thk*4, collection)
        c1.location = (0, hatch_y, hatch_z)
        apply_boolean_difference(parts['BACK'], c1, delete_cutter=True)
        
        # Cutter 2: Flange (Pocket from Outside Face).
        # Outside Face Y = box_d/2 + stock.
        # Pocket depth = stock/2.
        # Cutter size: Full Lid Size.
        # Cutter Y pos: Outside Face.
        # We want to remove material from Outside Face inwards.
        c2 = create_simple_box("Hatch_Cut_Pocket", h_open_w + 2*flange_w, h_open_h + 2*flange_w, stock_thk, collection)
        # Position: Center matches. Y needs to overlap outward half.
        # Back Panel Y range: [box_d/2, box_d/2 + stock].
        # We want to cut [box_d/2 + stock/2, box_d/2 + stock].
        # Center of cut region: box_d/2 + 0.75*stock.
        c2.location = (0, (box_d/2.0) + (stock_thk * 0.75), hatch_z)
        apply_boolean_difference(parts['BACK'], c2, delete_cutter=True)
        
    # Position Parts

    half_w = total_w / 2
    half_h = total_h / 2
    half_d = box_d / 2

    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.origin_set(type='ORIGIN_GEOMETRY', center='BOUNDS')
        obj.select_set(False)

    top_rail_width = parts['TOP'].dimensions.x
    finger_tip_x = top_rail_width / 2

    parts['TOP'].location = (0, 0, half_h - stock_thk/2)
    parts['BOTTOM'].location = (0, 0, -half_h + stock_thk/2)
    parts['LEFT'].location = (-finger_tip_x + stock_thk/2, 0, 0)
    parts['RIGHT'].location = (finger_tip_x - stock_thk/2, 0, 0)
    parts['FRONT'].location = (0, -half_d - stock_thk/2, 0)
    parts['BACK'].location = (0, half_d + stock_thk/2, 0)

    # Transforms & Materials
    for key, obj in parts.items():
        bpy.context.view_layer.objects.active = obj
        obj.select_set(True)
        bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
        obj.select_set(False)

    end_grain_config = {{
        'TOP': ['X'], 'BOTTOM': ['X'],
        'LEFT': ['Z'], 'RIGHT': ['Z'],
        'FRONT': ['X', 'Z'], 'BACK': ['X', 'Z'],
    }}

    for key, obj in parts.items():
        apply_end_grain_materials(obj, mat_wide, mat_end, end_grain_config.get(key, []))

    # Parent all parts to a main Empty for unified movement
    root_empty = bpy.data.objects.new("OUTSIDE FRAME", None)
    collection.objects.link(root_empty)
    
    # Hardcoded Transform: REMOVED per User Request (Center at 0,0,0)
    root_empty.location = (0, 0, 0)
    # Rotation: Keep 180 flip if it orients 'Front' correctly to camera default
    root_empty.rotation_euler = (0, 0, 3.141593)
    
    root_empty.empty_display_type = 'CUBE'
    root_empty.empty_display_size = 0.5
    
    # ADD LIGHTING ("OUTSIDE LIGHT")
    # Area light positioned to illuminate the front/top of the box
    light_data = bpy.data.lights.new(name="OUTSIDE LIGHT", type='AREA')
    light_data.color = (1.0, 1.0, 1.0)
    light_data.energy = 50.0  # Adjust as needed
    light_data.shape = 'SQUARE'
    light_data.size = 1.0     # 1 meter size
    
    light_obj = bpy.data.objects.new("OUTSIDE LIGHT", light_data)
    collection.objects.link(light_obj)
    
    # Initial Position (Relative to Box "Front" at -Y)
    # Place it in front (-Y) and above (+Z)
    light_obj.location = (0, -1.0, 1.0) 
    # Point it at the box (Rotate X positive to point "back" along +Y and down -Z?)
    # Default Area light points -Z.
    # Rot X +45deg -> Points -Z and +Y (Towards back)
    light_obj.rotation_euler = (math.radians(45), 0, 0)
    
    parts['LIGHT'] = light_obj  # Add to parts dict to participate in flip/parent loop
    
    # FLIP GEOMETRY 180 degrees internally
    for key, obj in parts.items():
        # Rotate location 180 deg around Z (which flips X and Y)
        # x' = x*cos(180) - y*sin(180) = -x
        # y' = x*sin(180) + y*cos(180) = -y
        obj.location.x = -obj.location.x
        obj.location.y = -obj.location.y
        # Add 180 deg to rotation
        obj.rotation_euler.z += math.pi

    for key, obj in parts.items():
        obj.parent = root_empty
        obj.matrix_parent_inverse = root_empty.matrix_world.inverted()

    print("Generation complete in collection 'OUTSIDE FRAME'")
    
    # 8. CONFIGURE VIEWPORT (Fix for Zoom Clipping)
    print("[8/8] Configuring Viewport settings...")
    for scr in bpy.data.screens:
        for area in scr.areas:
            if area.type == 'VIEW_3D':
                for space in area.spaces:
                    if space.type == 'VIEW_3D':
                        # Set Clip Start to 1mm to allow close zoom
                        space.clip_start = 0.001
                        # Ensure shading is nice
                        space.shading.type = 'MATERIAL'
                        space.shading.use_scene_lights = True
                        space.shading.use_scene_world = True

if __name__ == "__main__":
    create_shadowbox_assembly()
'''
    return script
